"""
Mock LLM / free AI mode for FootballQ AI.

Default behaviour (USE_MOCK_LLM=true, ENABLE_REAL_LLM=false):
    All scouting narratives are generated by template functions in this
    module, using player statistics, retrieved scouting notes, similarity
    results and tactical fit results. No external API calls are made and
    no cost is incurred.

Optional real LLM mode (ENABLE_REAL_LLM=true + OPENAI_API_KEY set):
    If enabled, `enhance_with_llm()` will attempt a short OpenAI chat
    completion to produce a more natural narrative from the same structured
    context. If the call fails for any reason (missing key, network error,
    rate limit, etc.) the function silently falls back to the template text
    - the public website must work without OpenAI.

Real LLM calls may incur OpenAI costs and are disabled by default.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from .config import get_settings

logger = logging.getLogger("footballq.mock_llm")


def _fmt(value: Any, suffix: str = "") -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.2f}{suffix}"
    return f"{value}{suffix}"


def _player_headline(player: dict[str, Any]) -> str:
    return (
        f"{player.get('player_name')} ({player.get('age')}, {player.get('nationality')}) "
        f"plays as a {player.get('position', 'player').lower()} for {player.get('club')} in the {player.get('league')}"
    )


# -----------------------------------------------------------------------------
# Player search
# -----------------------------------------------------------------------------

def generate_player_search_answer(query: str, players: list[dict[str, Any]]) -> str:
    if not players:
        return (
            "No players in the current sample dataset matched these criteria. "
            "Try widening the age range, position, or league filters."
        )

    if len(players) == 1:
        p = players[0]
        return (
            f"{_player_headline(p)}. Based on the available sample data, "
            f"{p.get('player_name')} recorded {_fmt(p.get('goals'))} goals and "
            f"{_fmt(p.get('assists'))} assists from {_fmt(p.get('minutes'))} minutes this season, "
            f"with an xG of {_fmt(p.get('xg'))} and xAG of {_fmt(p.get('xag'))}."
        )

    names = ", ".join(p.get("player_name", "Unknown") for p in players[:5])
    return (
        f"Based on the filters applied, {len(players)} player(s) match this search, "
        f"led by {names}. These results are ranked using the underlying statistical "
        f"profile (output, progression and defensive contribution metrics) most relevant to the query."
    )


# -----------------------------------------------------------------------------
# Comparison
# -----------------------------------------------------------------------------

def generate_comparison_narrative(comparison: dict[str, Any]) -> str:
    players = comparison["players"]
    names = [p.get("player_name", "Unknown") for p in players]
    summary = comparison.get("summary", "")

    highlights = []
    for diff in comparison.get("metric_differences", [])[:3]:
        leader = next((p for p in players if p["player_id"] == diff.get("leader")), None)
        if leader:
            highlights.append(
                f"{leader.get('player_name')} has a notable edge in {diff['label']} "
                f"(difference of {diff['difference']})"
            )

    text = f"Comparing {', '.join(names)}: {summary}"
    if highlights:
        text += " Key differences: " + "; ".join(highlights) + "."
    return text


# -----------------------------------------------------------------------------
# Similarity
# -----------------------------------------------------------------------------

def generate_similarity_explanation(reference_player: dict[str, Any], results: list[dict[str, Any]]) -> str:
    if not results:
        return (
            f"No statistically similar players were found for {reference_player.get('player_name')} "
            f"within the current sample dataset and filters. Try removing or widening filters."
        )

    top = results[0]
    top_player = top["player"]
    closest = top["closest_metrics"][0]["label"] if top["closest_metrics"] else "overall profile"

    text = (
        f"Players were ranked by similarity to {reference_player.get('player_name')} "
        f"({reference_player.get('position')}, {reference_player.get('club')}) using normalised "
        f"per-90 output, progression and defensive metrics. The closest match is "
        f"{top_player.get('player_name')} ({top_player.get('club')}) with a similarity score of "
        f"{top['similarity_score']}/100, most closely aligned on {closest}."
    )

    if len(results) > 1:
        others = ", ".join(r["player"].get("player_name", "Unknown") for r in results[1:4])
        text += f" Other close matches include {others}."

    return text


# -----------------------------------------------------------------------------
# Tactical fit
# -----------------------------------------------------------------------------

def generate_tactical_fit_summary(player: dict[str, Any], team: dict[str, Any], fit_result: dict[str, Any]) -> str:
    score = fit_result["fit_score"]
    if score >= 75:
        verdict = "an excellent tactical fit"
    elif score >= 55:
        verdict = "a reasonable tactical fit with some adjustment"
    elif score >= 35:
        verdict = "a partial fit that would require tactical compromises"
    else:
        verdict = "a stylistic mismatch based on current statistical profile"

    return (
        f"{player.get('player_name')} scores {score}/100 for tactical fit with {team.get('team_name')}, "
        f"representing {verdict}. {fit_result['explanation']}"
    )


# -----------------------------------------------------------------------------
# Full scouting report
# -----------------------------------------------------------------------------

def generate_scouting_report(player: dict[str, Any], scouting_note: Optional[dict[str, Any]]) -> dict[str, Any]:
    """Generate a structured scouting report combining stats and retrieved notes."""

    headline = _player_headline(player)
    stats_summary = (
        f"Key output: {_fmt(player.get('goals'))} goals and {_fmt(player.get('assists'))} assists "
        f"from {_fmt(player.get('minutes'))} minutes (xG {_fmt(player.get('xg'))}, xAG {_fmt(player.get('xag'))}). "
        f"Per-90 profile: {_fmt(player.get('progressive_carries_per90'))} progressive carries, "
        f"{_fmt(player.get('shot_creating_actions_per90'))} shot-creating actions, "
        f"{_fmt(player.get('pass_completion_pct'), '%')} pass completion."
    )

    if scouting_note:
        profile_summary = scouting_note.get("profile_summary", "")
        strengths = scouting_note.get("strengths", [])
        weaknesses = scouting_note.get("weaknesses", [])
        tactical_notes = scouting_note.get("tactical_notes", "")
        role_fit = scouting_note.get("role_fit", "")
        risk_notes = scouting_note.get("risk_notes", "")
    else:
        profile_summary = f"{headline}. {stats_summary}"
        strengths = ["Detailed scouting note not available for this player - statistical profile only."]
        weaknesses = []
        tactical_notes = "No specific tactical notes available; recommend a full scouting review."
        role_fit = "Role fit should be assessed against the statistical profile above."
        risk_notes = "No specific risk notes available."

    answer = f"{headline}. {profile_summary} {stats_summary}"

    return {
        "headline": headline,
        "answer": answer,
        "profile_summary": profile_summary,
        "stats_summary": stats_summary,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "tactical_notes": tactical_notes,
        "role_fit": role_fit,
        "risk_notes": risk_notes,
    }


# -----------------------------------------------------------------------------
# General / fallback
# -----------------------------------------------------------------------------

def generate_general_answer(query: str) -> str:
    return (
        "FootballQ AI can help you search for players, compare players, find statistically "
        "similar players, evaluate tactical fit for a club, and generate scouting reports. "
        "Try a more specific question, such as 'Find me young wingers similar to Lamine Yamal' "
        "or 'Compare Pedri and Bellingham'."
    )


# -----------------------------------------------------------------------------
# Optional real LLM enhancement (disabled by default)
# -----------------------------------------------------------------------------

def enhance_with_llm(system_prompt: str, user_prompt: str, fallback_text: str) -> str:
    """Attempt to enhance `fallback_text` using a real LLM if enabled.

    Always returns usable text. If ENABLE_REAL_LLM is false, no API key is
    configured, or the call fails for any reason, `fallback_text` (produced
    by the template generators above) is returned unchanged.
    """
    settings = get_settings()
    if not settings.enable_real_llm or not (settings.openai_api_key or settings.llm_base_url):
        return fallback_text

    try:
        from openai import OpenAI  # type: ignore

        client = OpenAI(
            # Ollama's OpenAI-compatible endpoint ignores the key but the
            # client requires a non-empty string.
            api_key=settings.openai_api_key or "ollama",
            base_url=settings.llm_base_url or None,
        )
        response = client.chat.completions.create(
            model=settings.llm_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=300,
            # Local models (Ollama) need more headroom than a hosted API.
            timeout=30 if settings.llm_base_url else 8,
        )
        content = response.choices[0].message.content
        return content.strip() if content else fallback_text
    except Exception as exc:  # pragma: no cover - optional dependency / network
        logger.warning("Real LLM enhancement failed, using template text: %s", type(exc).__name__)
        return fallback_text
