"""
Security helpers for the FootballQ AI API.

Provides:
- CORS header helpers driven by the ALLOWED_ORIGINS allowlist.
- Safe JSON error responses (never leak stack traces or secrets).
- Lightweight in-memory rate limiting (best-effort on Consumption plan).
- Prompt-injection / unsafe-input heuristics for the Safety Agent.
- Basic input sanitisation helpers.

This module intentionally avoids any dependency on the database or LLM
modules so it can be safely imported everywhere, including tests.
"""

from __future__ import annotations

import json
import logging
import re
import time
from typing import Any

from .config import get_settings

logger = logging.getLogger("footballq.security")

# -----------------------------------------------------------------------------
# CORS
# -----------------------------------------------------------------------------

def get_cors_headers(origin: str | None) -> dict[str, str]:
    """Return CORS headers if `origin` is in the ALLOWED_ORIGINS allowlist.

    If the origin is not allowed, no Access-Control-Allow-Origin header is
    returned (the browser will block the response).
    """
    settings = get_settings()
    headers: dict[str, str] = {
        "Vary": "Origin",
        "X-Content-Type-Options": "nosniff",
    }

    allowed = settings.allowed_origins
    if origin and (origin in allowed or "*" in allowed):
        headers["Access-Control-Allow-Origin"] = origin
        headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
        headers["Access-Control-Allow-Headers"] = "Content-Type"
        headers["Access-Control-Max-Age"] = "600"
    return headers


# -----------------------------------------------------------------------------
# Safe JSON responses
# -----------------------------------------------------------------------------

def json_response(body: dict[str, Any], status_code: int = 200, origin: str | None = None) -> tuple[str, int, dict[str, str]]:
    """Build a (body_str, status_code, headers) tuple for an HTTP response."""
    headers = {"Content-Type": "application/json"}
    headers.update(get_cors_headers(origin))
    return json.dumps(body, default=str), status_code, headers


def error_response(message: str, status_code: int = 400, origin: str | None = None, code: str = "bad_request") -> tuple[str, int, dict[str, str]]:
    """Build a safe JSON error response.

    Never include exception messages, stack traces, or internal details.
    `message` should be a short, user-friendly description.
    """
    safe_body = {"error": {"code": code, "message": message}}
    return json_response(safe_body, status_code=status_code, origin=origin)


def log_safe_exception(context: str, exc: Exception) -> None:
    """Log an exception without leaking secrets or full stack traces to clients.

    The exception type and a truncated message are logged server-side only.
    """
    logger.error("Error in %s: %s: %s", context, type(exc).__name__, str(exc)[:200])


# -----------------------------------------------------------------------------
# Input validation / sanitisation
# -----------------------------------------------------------------------------

MAX_QUERY_LENGTH = 500
MAX_PLAYER_IDS = 5

# Player IDs are generated by our seed data as simple slugs, e.g. "p001"
PLAYER_ID_PATTERN = re.compile(r"^[a-zA-Z0-9_\-]{1,50}$")

# Allowed characters for free-text search terms (letters, numbers, spaces,
# basic punctuation). Used defensively even though all SQL is parameterised.
SAFE_TEXT_PATTERN = re.compile(r"^[\w\s\-'.,?!]{0,500}$", re.UNICODE)


def is_valid_player_id(player_id: str) -> bool:
    return bool(player_id) and bool(PLAYER_ID_PATTERN.match(player_id))


def is_valid_team_name(team_name: str) -> bool:
    if not team_name or len(team_name) > 100:
        return False
    return bool(SAFE_TEXT_PATTERN.match(team_name))


def truncate_text(value: str, max_length: int = MAX_QUERY_LENGTH) -> str:
    return value[:max_length]


# -----------------------------------------------------------------------------
# Prompt injection / unsafe input heuristics (Safety Agent)
# -----------------------------------------------------------------------------

_INJECTION_PATTERNS = [
    re.compile(r"ignore (all|previous|the) (instructions|rules|prompts)", re.IGNORECASE),
    re.compile(r"system prompt", re.IGNORECASE),
    re.compile(r"reveal (your|the) (prompt|instructions|chain of thought|reasoning)", re.IGNORECASE),
    re.compile(r"act as (a |an )?(developer|admin|root|system)", re.IGNORECASE),
    re.compile(r"\bDROP\s+TABLE\b", re.IGNORECASE),
    re.compile(r"\bDELETE\s+FROM\b", re.IGNORECASE),
    re.compile(r"\bUNION\s+SELECT\b", re.IGNORECASE),
    re.compile(r"<script", re.IGNORECASE),
    re.compile(r"(api[_-]?key|secret|connection string|password)\s*[:=]", re.IGNORECASE),
]


def detect_prompt_injection(text: str) -> list[str]:
    """Return a list of human-readable flags for suspicious input.

    This is a heuristic safety net, not a guarantee. It is used by the
    Safety Agent to add a note to `limitations` rather than to silently
    fail - the API still responds, but flags risky content.
    """
    flags: list[str] = []
    if len(text) > MAX_QUERY_LENGTH:
        flags.append("input_too_long")
    for pattern in _INJECTION_PATTERNS:
        if pattern.search(text):
            flags.append("possible_prompt_injection_pattern")
            break
    return flags


# -----------------------------------------------------------------------------
# Lightweight in-memory rate limiting
# -----------------------------------------------------------------------------
# Note: Azure Functions Consumption plan instances are ephemeral and may
# scale to multiple instances, so this is a best-effort guard only - it is
# not a substitute for a proper API gateway / rate limiting service.

_request_log: dict[str, list[float]] = {}


def is_rate_limited(client_key: str) -> bool:
    settings = get_settings()
    if not settings.rate_limit_enabled:
        return False

    now = time.time()
    window = settings.rate_limit_window_seconds
    limit = settings.rate_limit_max_requests

    timestamps = _request_log.setdefault(client_key, [])
    # Drop timestamps outside the window
    cutoff = now - window
    timestamps[:] = [t for t in timestamps if t > cutoff]

    if len(timestamps) >= limit:
        return True

    timestamps.append(now)
    return False
